volumes:
  data:

networks:
  l2j:

x-common: &common
  entrypoint: ["/bin/bash","-c"]
  image: eclipse-temurin:17-jdk-jammy
  networks:
    - l2j
  user: "${UID_GID}"

services:
  # Database
  db:
    image: mariadb:11.0.2
    environment:
      MARIADB_PASSWORD: "${MARIADB_PASSWORD:-NO_PASSWORD_SET}"
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD:-NO_ROOT_PASSWORD_SET}"
      MARIADB_USER: "${MARIADB_USER:-NO_USER_SET}"
      MARIADB_DATABASE: "${MARIADB_DATABASE:-NO_DATABASE_NAME_SET}"
    healthcheck:
      test: mariadb --user ${MARIADB_USER} --password=${MARIADB_PASSWORD} -e "SELECT 1" 2>/dev/null
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - l2j
    volumes:
      - data:/var/lib/mysql

  # LoginServer
  login:
    <<: *common
    command:
      - |
        cd /opt/server/login
        ./LoginServerTask.sh
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: curl -sI localhost:2106; if [ $? -ge 2 ]; then exit 1; fi
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 2106:2106/tcp
    volumes:
      - ./release/${RELEASE}/libs:/opt/server/libs
      - ./release/${RELEASE}/login:/opt/server/login
      - ./logs/login:/opt/server/login/log

  # GameServer
  game:
    <<: *common
    command:
      - |
        cd /opt/server/game
        ./GameServerTask.sh
    depends_on:
      login:
        condition: service_healthy
      db:
        condition: service_healthy
    healthcheck:
      test: curl -sI localhost:7777; if [ $? -ge 2 ]; then exit 1; fi
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 7777:7777/tcp
    volumes:
      - ./release/${RELEASE}/libs:/opt/server/libs
      - ./release/${RELEASE}/game:/opt/server/game
      - ./geodata/geodata:/opt/server/game/data/shared_geodata
      - ./logs/game:/opt/server/game/log